apiVersion: v1
kind: Secret
metadata:
  name: harbor-image-secret
  namespace: ecommerce
  labels:
    app: ecommerce
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "your.privateregistry.domain.id": {
          "username": "<your-harbor-user>",
          "password": "<your-harbor-password-or-robot-token>",
        }
      }
    }